apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azpAgentName | default "azp-agent" }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  azpToken: {{ .Values.azpToken | b64enc }}
