apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.azpAgentName | default "azp-agent" }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector:
      {{ toYaml .nodeSelector | indent 2 }}
      {{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources.requests }}
        resources:
          requests:
          {{ toYaml .Values.resources.requests | indent 2 }}
          limits:
          {{ toYaml .Values.resources.limits | indent 2 }}
        {{ end }}
        env:
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.azpAgentName | default "azp-agent" }}-secret
                key: azpToken
         {{- with .Values }}
          - name: AZP_URL
            value: {{ .azpUrl }}
          - name: AZP_POOL
            value: {{ .azpPool }}
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: AZP_WORK
            value: {{ .azpWorkspace | default "/workspace" | quote }}
         {{- end }}
         {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
         {{- end }}
        volumeMounts:
          - name: workspace
            mountPath: {{ .Values.azpWorkspace | default "/workspace" | quote }}
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 10 }}
{{ end }}
     {{- if .Values.cleanRun }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "! ls /azp/agent/_diag | grep Worker || pgrep Agent.Worker"
          initialDelaySeconds: 120
          periodSeconds: 5
     {{- end }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
{{ if .Values.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}
{{ end }}
  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: {{ .Values.resources.storageclass | default "default" | quote }}
      resources:
        requests:
          storage: {{ .Values.resources.disk | default "50Gi" | quote }}
